### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by huntb** [adafruit/Adafruit_CircuitPython_PCT2075#23]
Running pct2075_simpletest.py on Feather RP2040 with CircuitPython 8.2.9 and receive the following error:

```
code.py output:
Traceback (most recent call last):
  File "code.py", line 6, in <module>
  File "adafruit_pct2075.py", line 35, in <module>
ImportError: no module named 'adafruit_register'
```

**Comment by huntb** [comment]
This issue was fixed by adding **adafruit_register** to lib folder on Feather RP2040.
